<a href="https://colab.research.google.com/github/ShushumnaVazeer/MDS_LAB/blob/main/MDS_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
arr=np.array([19,12,34,56,78])

In [8]:
np.random.choice(arr)

np.int64(12)

In [12]:
arr1=np.random.randint(1,100,5)
print(arr1)

[24  3 22 53  2]


In [22]:
import numpy as np

# Original array
data_array = np.array(['A', 'B', 'C', 'D', 'E', 'F'])
print(f"Original data array: {data_array}")

# Set a seed for reproducibility
np.random.seed(10)

# Shuffle the array
shuffled_array = data_array.copy()
np.random.shuffle(shuffled_array)
print(f"Shuffled array (after seed 10): {shuffled_array}")

# Make a random choice from the shuffled array
chosen_element = np.random.choice(shuffled_array)
print(f"Random choice from shuffled array: {chosen_element}")

# Demonstrate reproducibility: reset seed and repeat
np.random.seed(10)
shuffled_array_repro = data_array.copy()
np.random.shuffle(shuffled_array_repro)
chosen_element_repro = np.random.choice(shuffled_array_repro)

print(f"\nRepeating with same seed (10):")
print(f"Shuffled array (reproducible): {shuffled_array_repro}")
print(f"Random choice (reproducible): {chosen_element_repro}")

# Demonstrate different result without seed or with different seed
print(f"\nDemonstrating different results without a seed:")
data_array_no_seed = np.array(['A', 'B', 'C', 'D', 'E', 'F'])
np.random.shuffle(data_array_no_seed)
chosen_element_no_seed = np.random.choice(data_array_no_seed)
print(f"Shuffled array (no seed): {data_array_no_seed}")
print(f"Random choice (no seed): {chosen_element_no_seed}")

Original data array: ['A' 'B' 'C' 'D' 'E' 'F']
Shuffled array (after seed 10): ['C' 'F' 'A' 'D' 'E' 'B']
Random choice from shuffled array: D

Repeating with same seed (10):
Shuffled array (reproducible): ['C' 'F' 'A' 'D' 'E' 'B']
Random choice (reproducible): D

Demonstrating different results without a seed:
Shuffled array (no seed): ['C' 'D' 'A' 'F' 'B' 'E']
Random choice (no seed): D


In [24]:
import numpy as np

# --- Reshaping Arrays ---
print("--- Reshaping Arrays ---")
# Create a 1D array
arr_1d = np.arange(1, 10)
print(f"Original 1D array: {arr_1d}")

# Reshape to a 2D array (3 rows, 3 columns)
arr_2d = arr_1d.reshape(3, 3)
print(f"Reshaped to 2D array (3x3):\n{arr_2d}")

# Reshape to a 2D array (9 rows, 1 column)
arr_col = arr_1d.reshape(9, 1)
print(f"Reshaped to 2D array (9x1):\n{arr_col}")

# Reshape with -1 to let NumPy infer the dimension
arr_inferred = arr_1d.reshape(-1, 3) # Infer number of rows
print(f"Reshaped with inferred rows (-1, 3):\n{arr_inferred}")

# --- Joining and Splitting Arrays ---
print("\n--- Joining Arrays ---")

arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
print(f"Array A:\n{arr_a}")
print(f"Array B:\n{arr_b}")

# Concatenate along axis 0 (rows)
concatenated_rows = np.concatenate((arr_a, arr_b), axis=0)
print(f"\nConcatenated along axis 0 (rows):\n{concatenated_rows}")

# Concatenate along axis 1 (columns)
concatenated_cols = np.concatenate((arr_a, arr_b), axis=1)
print(f"Concatenated along axis 1 (columns):\n{concatenated_cols}")

# Vertical stack (vstack) - equivalent to concatenate(axis=0)
v_stacked = np.vstack((arr_a, arr_b))
print(f"\nVertically stacked (vstack):\n{v_stacked}")

# Horizontal stack (hstack) - equivalent to concatenate(axis=1)
h_stacked = np.hstack((arr_a, arr_b))
print(f"Horizontally stacked (hstack):\n{h_stacked}")

print("\n--- Splitting Arrays ---")
big_array = np.arange(1, 17).reshape(4, 4)
print(f"Original array to split:\n{big_array}")

# Split array into 2 equal parts vertically
split_v = np.vsplit(big_array, 2)
print(f"\nVertically split into 2 parts:\nPart 1:\n{split_v[0]}\nPart 2:\n{split_v[1]}")

# Split array into 4 equal parts horizontally
split_h = np.hsplit(big_array, 4)
print(f"\nHorizontally split into 4 parts:\nPart 1:\n{split_h[0]}\nPart 2:\n{split_h[1]}\nPart 3:\n{split_h[2]}\nPart 4:\n{split_h[3]}")

--- Reshaping Arrays ---
Original 1D array: [1 2 3 4 5 6 7 8 9]
Reshaped to 2D array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped to 2D array (9x1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Reshaped with inferred rows (-1, 3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Joining Arrays ---
Array A:
[[1 2]
 [3 4]]
Array B:
[[5 6]
 [7 8]]

Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]

Vertically stacked (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked (hstack):
[[1 2 5 6]
 [3 4 7 8]]

--- Splitting Arrays ---
Original array to split:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Vertically split into 2 parts:
Part 1:
[[1 2 3 4]
 [5 6 7 8]]
Part 2:
[[ 9 10 11 12]
 [13 14 15 16]]

Horizontally split into 4 parts:
Part 1:
[[ 1]
 [ 5]
 [ 9]
 [13]]
Part 2:
[[ 2]
 [ 6]
 [10]
 [14]]
Part 3:
[[ 3]
 [ 7]
 [11]
 [15]]
Part 4:
[[ 4]
 [ 8]
 [12]
 [16]]


In [25]:
import numpy as np

# --- Indexing Arrays ---
print("\n--- Indexing Arrays ---")
arr = np.array([10, 20, 30, 40, 50])
print(f"Original 1D array: {arr}")

# Accessing a single element
print(f"Element at index 0: {arr[0]}")
print(f"Element at index 3: {arr[3]}")

# Negative indexing (from the end)
print(f"Last element: {arr[-1]}")
print(f"Second to last element: {arr[-2]}")

# For 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nOriginal 2D array:\n{arr_2d}")

# Accessing a single element (row, column)
print(f"Element at (0, 0): {arr_2d[0, 0]}")
print(f"Element at (1, 2): {arr_2d[1, 2]}")

# --- Slicing Arrays ---
print("\n--- Slicing Arrays ---")
arr_1d_slice = np.arange(10, 101, 10)
print(f"Original 1D array for slicing: {arr_1d_slice}")

# Basic slicing (start:end)
print(f"Elements from index 2 to 5 (exclusive): {arr_1d_slice[2:6]}")

# Slicing from the beginning
print(f"Elements up to index 4 (exclusive): {arr_1d_slice[:5]}")

# Slicing to the end
print(f"Elements from index 6 to the end: {arr_1d_slice[6:]}")

# Slicing with a step (start:end:step)
print(f"Every second element: {arr_1d_slice[::2]}")
print(f"Elements from index 1 to 7 (exclusive), every third: {arr_1d_slice[1:8:3]}")

# For 2D arrays
arr_2d_slice = np.array([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43]
])
print(f"\nOriginal 2D array for slicing:\n{arr_2d_slice}")

# Slicing rows
print(f"\nFirst two rows:\n{arr_2d_slice[:2]}")

# Slicing columns
print(f"\nFirst and third columns:\n{arr_2d_slice[:, [0, 2]]}")

# Slicing both rows and columns
print(f"\nElements from rows 1-2 and columns 0-1:\n{arr_2d_slice[1:3, :2]}")

# Slicing a single row and all its columns
print(f"\nSecond row (index 1): {arr_2d_slice[1, :]}")

# Slicing a single column and all its rows
print(f"\nThird column (index 2): {arr_2d_slice[:, 2]}")


--- Indexing Arrays ---
Original 1D array: [10 20 30 40 50]
Element at index 0: 10
Element at index 3: 40
Last element: 50
Second to last element: 40

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
Element at (1, 2): 6

--- Slicing Arrays ---
Original 1D array for slicing: [ 10  20  30  40  50  60  70  80  90 100]
Elements from index 2 to 5 (exclusive): [30 40 50 60]
Elements up to index 4 (exclusive): [10 20 30 40 50]
Elements from index 6 to the end: [ 70  80  90 100]
Every second element: [10 30 50 70 90]
Elements from index 1 to 7 (exclusive), every third: [20 50 80]

Original 2D array for slicing:
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

First two rows:
[[10 11 12 13]
 [20 21 22 23]]

First and third columns:
[[10 12]
 [20 22]
 [30 32]
 [40 42]]

Elements from rows 1-2 and columns 0-1:
[[20 21]
 [30 31]]

Second row (index 1): [20 21 22 23]

Third column (index 2): [12 22 32 42]


In [27]:
import numpy as np

# --- Element-wise Arithmetic Operations ---
print("--- Element-wise Arithmetic Operations ---")

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}\n")

# Addition
print(f"Addition (arr1 + arr2): {arr1 + arr2}")
print(f"Addition (np.add(arr1, arr2)): {np.add(arr1, arr2)}\n")

# Subtraction
print(f"Subtraction (arr1 - arr2): {arr1 - arr2}")
print(f"Subtraction (np.subtract(arr1, arr2)): {np.subtract(arr1, arr2)}\n")

# Multiplication
print(f"Multiplication (arr1 * arr2): {arr1 * arr2}")
print(f"Multiplication (np.multiply(arr1, arr2)): {np.multiply(arr1, arr2)}\n")

# Division
print(f"Division (arr1 / arr2): {arr1 / arr2}")
print(f"Division (np.divide(arr1, arr2)): {np.divide(arr1, arr2)}\n")

# Exponentiation
print(f"Exponentiation (arr1 ** 2): {arr1 ** 2}")
print(f"Exponentiation (np.power(arr1, 2)): {np.power(arr1, 2)}\n")

# Modulus
print(f"Modulus (arr2 % arr1): {arr2 % arr1}")
print(f"Modulus (np.mod(arr2, arr1)): {np.mod(arr2, arr1)}\n")

# --- Broadcasting Example with Arithmetic Operations ---
print("--- Broadcasting Example ---")
arr_broadcast = np.array([10, 20, 30])
scalar = 5

print(f"Array for broadcasting: {arr_broadcast}")
print(f"Scalar value: {scalar}\n")

print(f"Array + Scalar: {arr_broadcast + scalar}")
print(f"Array * Scalar: {arr_broadcast * scalar}\n")

# --- Common Mathematical Ufuncs ---
print("--- Common Mathematical Ufuncs ---")
x = np.array([-2, -1, 0, 1, 2, 3.5])
print(f"Input array x: {x}\n")

print(f"Absolute values (np.abs(x)): {np.abs(x)}")
print(f"Square root (np.sqrt(x[x>=0])): {np.sqrt(x[x>=0])}") # Only for non-negative numbers
print(f"Exponential (np.exp(x)): {np.exp(x)}")
print(f"Logarithm (np.log(x[x>0])): {np.log(x[x>0])}") # Only for positive numbers
print(f"Sine (np.sin(x)): {np.sin(x)}")
print(f"Cosine (np.cos(x)): {np.cos(x)}")
print(f"Floor (np.floor(x)): {np.floor(x)}")
print(f"Ceiling (np.ceil(x)): {np.ceil(x)}")
print(f"Round (np.round(x)): {np.round(x)}")

--- Element-wise Arithmetic Operations ---
Array 1: [1 2 3 4]
Array 2: [5 6 7 8]

Addition (arr1 + arr2): [ 6  8 10 12]
Addition (np.add(arr1, arr2)): [ 6  8 10 12]

Subtraction (arr1 - arr2): [-4 -4 -4 -4]
Subtraction (np.subtract(arr1, arr2)): [-4 -4 -4 -4]

Multiplication (arr1 * arr2): [ 5 12 21 32]
Multiplication (np.multiply(arr1, arr2)): [ 5 12 21 32]

Division (arr1 / arr2): [0.2        0.33333333 0.42857143 0.5       ]
Division (np.divide(arr1, arr2)): [0.2        0.33333333 0.42857143 0.5       ]

Exponentiation (arr1 ** 2): [ 1  4  9 16]
Exponentiation (np.power(arr1, 2)): [ 1  4  9 16]

Modulus (arr2 % arr1): [0 0 1 0]
Modulus (np.mod(arr2, arr1)): [0 0 1 0]

--- Broadcasting Example ---
Array for broadcasting: [10 20 30]
Scalar value: 5

Array + Scalar: [15 25 35]
Array * Scalar: [ 50 100 150]

--- Common Mathematical Ufuncs ---
Input array x: [-2.  -1.   0.   1.   2.   3.5]

Absolute values (np.abs(x)): [2.  1.  0.  1.  2.  3.5]
Square root (np.sqrt(x[x>=0])): [0.        

### Linear Algebra Operations with NumPy

NumPy provides a powerful and efficient library (`numpy.linalg`) for various linear algebra operations, which are fundamental in many scientific and data-related applications. Let's explore some key operations.

In [31]:
import numpy as np

# --- Vector Operations ---
print("--- Vector Operations ---")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f"Vector 1 (v1): {v1}")
print(f"Vector 2 (v2): {v2}\n")

# Dot product
dot_product = np.dot(v1, v2)
print(f"Dot product (v1 . v2): {dot_product}")

# Cross product (only for 3D vectors)
cross_product = np.cross(v1, v2)
print(f"Cross product (v1 x v2): {cross_product}")

# Magnitude (L2 norm) of a vector
magnitude_v1 = np.linalg.norm(v1)
print(f"Magnitude of v1: {magnitude_v1:.4f}")

--- Vector Operations ---
Vector 1 (v1): [1 2 3]
Vector 2 (v2): [4 5 6]

Dot product (v1 . v2): 32
Cross product (v1 x v2): [-3  6 -3]
Magnitude of v1: 3.7417


In [32]:
import numpy as np

# --- Matrix Operations ---
print("\n--- Matrix Operations ---")
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}\n")

# Matrix multiplication (dot product for matrices)
matrix_mult = np.dot(A, B)
# or using the @ operator (Python 3.5+)
matrix_mult_at = A @ B
print(f"Matrix Multiplication (A @ B):\n{matrix_mult}\n")

# Transpose of a matrix
A_transpose = A.T
print(f"Transpose of A:\n{A_transpose}\n")

# Determinant of a matrix
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A:.4f}\n")

# Inverse of a matrix
# Note: Not all matrices have an inverse (e.g., singular matrices)
try:
    A_inverse = np.linalg.inv(A)
    print(f"Inverse of A:\n{A_inverse}\n")
    # Verify: A @ A_inverse should be identity matrix
    print(f"A @ A_inverse (should be Identity):\n{A @ A_inverse}\n")
except np.linalg.LinAlgError:
    print("Matrix A is singular; cannot compute inverse.")


--- Matrix Operations ---
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A: -2.0000

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inverse (should be Identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]



In [33]:
import numpy as np

# --- Solving Linear Equations ---
print("\n--- Solving Linear Equations ---")
# Consider the system of linear equations:
# 2x + 3y = 9
# x  + 2y = 5

# Represent as Ax = b
# A is the coefficient matrix
A_eq = np.array([[2, 3],
                 [1, 2]])

# b is the constants vector
b_eq = np.array([9, 5])

print(f"Coefficient Matrix (A):\n{A_eq}")
print(f"Constants Vector (b): {b_eq}\n")

# Solve for x using np.linalg.solve(A, b)
# This is more stable and efficient than computing A_inverse @ b
x_sol = np.linalg.solve(A_eq, b_eq)

print(f"Solution (x, y): {x_sol}")
print(f"Verification (A @ x_sol): {A_eq @ x_sol} (should be equal to b_eq)")



--- Solving Linear Equations ---
Coefficient Matrix (A):
[[2 3]
 [1 2]]
Constants Vector (b): [9 5]

Solution (x, y): [3. 1.]
Verification (A @ x_sol): [9. 5.] (should be equal to b_eq)
