<a href="https://colab.research.google.com/github/ShushumnaVazeer/MDS_LAB/blob/main/week1_mds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np
print(np.__version__)


2.0.2


## Python List vs NumPy Array Performance Comparison

This section compares the performance of Python's built-in lists and NumPy arrays for common operations, specifically focusing on creation and element-wise arithmetic. NumPy arrays are generally more efficient for numerical operations, especially with large datasets, due to their underlying C implementation and optimized memory usage.

In [ ]:
import time
import numpy as np

# Define the size of the data structures
size = 10**6  # One million elements

print(f"Comparing performance for data structures with {size} elements.\n")

# --- 1. Creation Time ---
print("### 1. Creation Time ###")

# Python List creation
start_time = time.time()
python_list = list(range(size))
end_time = time.time()
python_list_creation_time = end_time - start_time
print(f"Python List Creation: {python_list_creation_time:.6f} seconds")

# NumPy Array creation
start_time = time.time()
numpy_array = np.arange(size)
end_time = time.time()
numpy_array_creation_time = end_time - start_time
print(f"NumPy Array Creation: {numpy_array_creation_time:.6f} seconds")

print(f"NumPy array creation is {python_list_creation_time / numpy_array_creation_time:.2f}x faster.\n")

# --- 2. Element-wise Addition ---
print("### 2. Element-wise Addition ###")

# Python List addition
start_time = time.time()
python_list_sum = [x + 1 for x in python_list]
end_time = time.time()
python_list_add_time = end_time - start_time
print(f"Python List Addition: {python_list_add_time:.6f} seconds")

# NumPy Array addition
start_time = time.time()
numpy_array_sum = numpy_array + 1
end_time = time.time()
numpy_array_add_time = end_time - start_time
print(f"NumPy Array Addition: {numpy_array_add_time:.6f} seconds")

print(f"NumPy array addition is {python_list_add_time / numpy_array_add_time:.2f}x faster.\n")


# --- 3. Element-wise Multiplication ---
print("### 3. Element-wise Multiplication ###")

# Python List multiplication
start_time = time.time()
python_list_prod = [x * 2 for x in python_list]
end_time = time.time()
python_list_mul_time = end_time - start_time
print(f"Python List Multiplication: {python_list_mul_time:.6f} seconds")

# NumPy Array multiplication
start_time = time.time()
numpy_array_prod = numpy_array * 2
end_time = time.time()
numpy_array_mul_time = end_time - start_time
print(f"NumPy Array Multiplication: {numpy_array_mul_time:.6f} seconds")

print(f"NumPy array multiplication is {python_list_mul_time / numpy_array_mul_time:.2f}x faster.\n")

Comparing performance for data structures with 1000000 elements.

### 1. Creation Time ###
Python List Creation: 0.026276 seconds
NumPy Array Creation: 0.004424 seconds
NumPy array creation is 5.94x faster.

### 2. Element-wise Addition ###
Python List Addition: 0.040983 seconds
NumPy Array Addition: 0.002735 seconds
NumPy array addition is 14.98x faster.

### 3. Element-wise Multiplication ###
Python List Multiplication: 0.042347 seconds
NumPy Array Multiplication: 0.002983 seconds
NumPy array multiplication is 14.19x faster.



In [ ]:
import sys

# --- 4. Memory Usage ---
print("### 4. Memory Usage ###")

# Python List memory usage
# sys.getsizeof() reports the size of the list object itself, plus a pointer for each item.
# For a more accurate comparison of actual data storage, we also need to consider the size of individual elements.
# However, for a simple comparison, sys.getsizeof() on the list object and numpy's .nbytes is often used.
python_list_memory = sys.getsizeof(python_list)
print(f"Python List Memory: {python_list_memory / (1024*1024):.3f} MB") # Convert bytes to MB

# NumPy Array memory usage
numpy_array_memory = numpy_array.nbytes
print(f"NumPy Array Memory: {numpy_array_memory / (1024*1024):.3f} MB") # Convert bytes to MB

if numpy_array_memory > 0:
    print(f"NumPy array uses {python_list_memory / numpy_array_memory:.2f}x less memory (relative to Python list object size and internal pointers).\n")
else:
    print("Cannot compare memory usage as NumPy array memory is zero (likely an empty array).\n")

### 4. Memory Usage ###
Python List Memory: 7.629 MB
NumPy Array Memory: 7.629 MB
NumPy array uses 1.00x less memory (relative to Python list object size and internal pointers).



## Conclusion

As demonstrated, NumPy arrays consistently outperform Python lists for numerical operations on large datasets. This is primarily due to:

*   **Vectorization**: NumPy operations are implemented in C, allowing for highly optimized, vectorized computations without explicit Python loops.
*   **Memory Efficiency**: NumPy arrays store elements of the same data type contiguously in memory, leading to better cache performance and reduced memory overhead compared to Python lists, which store pointers to objects.

For tasks involving significant numerical computation, using NumPy is highly recommended to achieve better performance.

In [98]:
#creating a list
list=[19,2,3,4,5]

In [99]:
#printing type
type(list)

list

In [101]:
#converting list to array
arr1=np.array(list)

In [104]:
#printing type
type(arr1)

numpy.ndarray

In [107]:
#printing the size of the array
arr1.size

5

In [109]:
#printing shape of the array
arr1.shape

(5,)

In [111]:
#printing the memory of array
arr1.nbytes

40

In [113]:
#printing the dimension
arr1.ndim

1

In [114]:
#printing data type
arr1.dtype

dtype('int64')

In [115]:
#printing data type name
arr1.dtype.name

'int64'

In [112]:
#creating the tuple
tuple=(1,2,3,4,5)

In [116]:
#type
type(tuple)

tuple

In [118]:
#creating tuple with 1 element
tuple1=(19,)

In [ ]:
type(tuple1)

tuple

In [119]:
#converting tuple to array
arr2=np.array(tuple1)

In [120]:
print(arr2)

[19]


In [ ]:
arr1.ndim

1

## Creating 2x2 Arrays

In [121]:
# Creating a 2x2 array using a Python list of lists
python_2x2_list = [[19, 2], [3, 4]]
print("Python 2x2 List:")
print(python_2x2_list)
print(f"Type: {type(python_2x2_list)}\n")

# Creating a 2x2 NumPy array from a list of lists
numpy_array_from_list = np.array([[19, 6], [7, 8]])
print("NumPy Array from List:")
print(numpy_array_from_list)
print(f"Type: {type(numpy_array_from_list)}\n")

# Creating a 2x2 NumPy array from a tuple of tuples
numpy_array_from_tuple = np.array(((19, 10), (11, 12)))
print("NumPy Array from Tuple:")
print(numpy_array_from_tuple)
print(f"Type: {type(numpy_array_from_tuple)}\n")

Python 2x2 List:
[[19, 2], [3, 4]]
Type: <class 'list'>

NumPy Array from List:
[[19  6]
 [ 7  8]]
Type: <class 'numpy.ndarray'>

NumPy Array from Tuple:
[[19 10]
 [11 12]]
Type: <class 'numpy.ndarray'>



In [ ]:
list=[[1,2],[3,4]]

In [122]:
#creating matriix using list
matrix=np.array(list)

In [123]:
#printing matrix
print(matrix)

[19  2  3  4  5]


In [124]:
#flatten
matrix.flatten()

array([19,  2,  3,  4,  5])

In [125]:
#ravel
matrix.ravel()


array([19,  2,  3,  4,  5])

In [126]:
arr4=np.array([19,2,3,4])

In [127]:
print(arr4)

[19  2  3  4]


In [130]:
#creating 2*2 matrix
arr5=np.array([[19,2],[3,4]])

In [131]:
print(arr5)

[[19  2]
 [ 3  4]]


In [133]:
#creating 3*2 matrix
arr6=np.matrix([[19,2],[3,4],[5,6]])

In [134]:
print(arr6)

[[19  2]
 [ 3  4]
 [ 5  6]]


## Creating a 1D NumPy Array (1 to 100)

In [ ]:
import numpy as np

# Create a 1D NumPy array from 1 to 100 (inclusive)
array_1_to_100 = np.arange(1, 101)
print(array_1_to_100)
print(f"Shape: {array_1_to_100.shape}")
print(f"Dimensions: {array_1_to_100.ndim}")

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Shape: (100,)
Dimensions: 1


In [135]:
#creating 1d array from 1 to 100
arr7=np.arange(1,100)

In [136]:
#creating 1d array with even numbers
arr8=np.arange(0,100,2)

In [137]:
print(arr8)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [138]:
#reshaping the matrix
matrix3=np.arange(0,10).reshape(2,5)

In [139]:
print(matrix3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Creating a 4x4 Matrix of Zeros

In [ ]:
import numpy as np

# Create a 4x4 matrix with all elements as 0
a = np.zeros((4, 4),dtype='int')
print((a))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [144]:
#creating 1's matrix of int type
b=np.ones((3,3),dtype='int')
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [145]:
#creating 2's matrix
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [147]:
#creating 10's matrix
d=np.full((3,4),10)
print(d)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [148]:
#creating the identity matrix
e=np.eye(3,dtype='int')
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [149]:
#creating linear space array
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [150]:
#creating random array
a=np.random.random((3,3))
print(a)

[[0.40462618 0.69281822 0.12878334]
 [0.09363745 0.24068746 0.95142666]
 [0.06295579 0.2567487  0.8164827 ]]


In [ ]:
arr1=np.arange(1,10)

In [ ]:
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [153]:
#changing the eleemt
arr1[1]=111
print(arr1)

[ 19 111   3   4   5]


In [155]:
#changing multiple values
arr1[[2, 3, 4]] = [56, 37, 86]
print(arr1)

[ 19 111  56  37  86]


In [156]:
#finding max
arr1.max()

np.int64(111)

In [158]:
#finding min
arr1.min()

np.int64(19)

In [159]:
#finding size
arr1.size

5

In [163]:
import numpy as np
import builtins

# Define a dictionary
data_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40}

print("Original Dictionary:", data_dict)

# Create a NumPy array from dictionary values
array_from_values = np.array(builtins.list(data_dict.values()))
print("\nNumPy Array from Dictionary Values:", array_from_values)
print("Type:", type(array_from_values))

# Create a NumPy array from dictionary keys
array_from_keys = np.array(builtins.list(data_dict.keys()))
print("\nNumPy Array from Dictionary Keys:", array_from_keys)
print("Type:", type(array_from_keys))

# Create a NumPy array from dictionary items (list of tuples)
array_from_items = np.array(builtins.list(data_dict.items()))
print("\nNumPy Array from Dictionary Items (as list of tuples):\n", array_from_items)
print("Type:", type(array_from_items))

Original Dictionary: {'a': 10, 'b': 20, 'c': 30, 'd': 40}

NumPy Array from Dictionary Values: [10 20 30 40]
Type: <class 'numpy.ndarray'>

NumPy Array from Dictionary Keys: ['a' 'b' 'c' 'd']
Type: <class 'numpy.ndarray'>

NumPy Array from Dictionary Items (as list of tuples):
 [['a' '10']
 ['b' '20']
 ['c' '30']
 ['d' '40']]
Type: <class 'numpy.ndarray'>
